#pragma checksum "D:\Projects\Odachi\samples\MailSample\Templates\HelloMessage.cshtml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "70fa2832ab0ba4f87fbf9ebf53f531fb344a5c20"
// <auto-generated/>
#pragma warning disable 1591
namespace MailSample.Templates
{
    #line hidden
    public class HelloMessage : Odachi.Mail.MailTemplate
    {
        #pragma warning disable 1998
        public async override global::System.Threading.Tasks.Task ExecuteAsync()
        {
#line 2 "D:\Projects\Odachi\samples\MailSample\Templates\HelloMessage.cshtml"
  
	Layout = new MailSample.Templates.Layout.BasicLayout();

#line default
#line hidden
            WriteLiteral("<p>\r\n\tHello world!\r\n\r\n\t<img");
            BeginWriteAttribute("src", " src=\"", 128, "\"", 187, 1);
#line 8 "D:\Projects\Odachi\samples\MailSample\Templates\HelloMessage.cshtml"
WriteAttributeValue("", 134, Embed("image/png", "MailSample.Resources.Lenna.png"), 134, 53, false);

#line default
#line hidden
            EndWriteAttribute();
            WriteLiteral(" alt=\"Lenna\" />\r\n</p>\r\n");
        }
        #pragma warning restore 1998
    }
}
#pragma warning restore 1591
