dist: trusty
sudo: required
language: csharp
mono: none
dotnet: 2.0.0

addons:
  apt:
    sources:
    - sourceline: 'deb [arch=amd64] https://packages.microsoft.com/repos/microsoft-ubuntu-trusty-prod trusty main'
      key_url: 'https://packages.microsoft.com/keys/microsoft.asc'
    packages:
    - dotnet-sharedframework-microsoft.netcore.app-1.0.5
    - dotnet-sharedframework-microsoft.netcore.app-1.1.2

install:
  - chmod a+x ./build.sh

script:
  - source ./build.sh
