language: bash
sudo: required
dist: trusty

addons:
  apt:
    packages:
      - gettext
      - libcurl4-openssl-dev
      - libicu-dev
      - libssl-dev
      - libunwind8
      - zlib1g

install:
  - chmod a+x ./install.sh ./build.sh
  - source ./install.sh

script:
  - source ./build.sh