version: '5.0.0-{build}'
image: Visual Studio 2019 Preview

skip_tags: true

install:
  - ps: Invoke-WebRequest https://dot.net/v1/dotnet-install.ps1 -OutFile dotnet-install.ps1
  - ps: ./dotnet-install.ps1 --Version 5.0.100 -InstallDir 'C:\Program Files\dotnet'

branches:
  only:
    - master
    - preview
    - release

clone_depth: 1

cache:
  - C:\Users\appveyor\.nuget\packages -> **\*.csproj

init:
  - git config --global core.autocrlf true

build_script:
  - ps: "& ./build.ps1"

test: off

artifacts:
  - path: 'build/*.nupkg'
    type: NuGetPackage
  - path: 'build/*.snupkg'
    type: NuGetPackage

deploy:
  - provider: Environment
    name: GitHub Releases (preview)
    on:
      branch: preview
  - provider: Environment
    name: GitHub Releases (release)
    on:
      branch: release
  - provider: Environment
    name: NuGet
    on:
      branch: preview
  - provider: Environment
    name: NuGet
    on:
      branch: release
