version: '3.1.0-{build}'
image: Visual Studio 2019

skip_tags: true

branches:
  only:
    - master
    - preview
    - release

clone_depth: 1

cache:
  - C:\Users\appveyor\.nuget\packages -> **\*.csproj

init:
  - git config --global core.autocrlf true

build_script:
  - ps: "& ./build.ps1"

test: off

artifacts:
  - path: 'build/*.nupkg'
  - path: 'build/*.snupkg'

deploy:
  - provider: Environment
    name: GitHub Releases (preview)
    on:
      branch: preview
  - provider: Environment
    name: GitHub Releases (release)
    on:
      branch: release
  - provider: Environment
    name: NuGet
    on:
      branch: preview
  - provider: Environment
    name: NuGet
    on:
      branch: release
