version: '1.0.0-beta8-{build}'

skip_tags: true

branches:
  only:
    - master
    - stable

clone_depth: 1

init:
  - git config --global core.autocrlf true

install:
  - ps: "& ./install.ps1"

build_script:
  - ps: "& ./build.ps1"

test: off

artifacts:
  - path: 'build/Release/*.nupkg'

deploy:
  - provider: Environment
    name: GitHub Releases (pre)
    on:
      branch: master
  - provider: Environment
    name: GitHub Releases (stable)
    on:
      branch: stable