#pragma checksum "D:\Projects\Odachi\samples\MailSample\Templates\Layout\BasicLayout.cshtml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "c0fb11773ddccfbf007bf872c277e05cf56dd9ab"
// <auto-generated/>
#pragma warning disable 1591
namespace MailSample.Templates.Layout
{
    #line hidden
    public class BasicLayout : Odachi.Mail.MailTemplateLayout
    {
        #pragma warning disable 1998
        public async override global::System.Threading.Tasks.Task ExecuteAsync()
        {
            WriteLiteral("<!DOCTYPE html>\r\n<html lang=\"en\" xmlns=\"http://www.w3.org/1999/xhtml\">\r\n<head>\r\n    <meta charset=\"utf-8\" />\r\n</head>\r\n<body>\r\n");
#line 8 "D:\Projects\Odachi\samples\MailSample\Templates\Layout\BasicLayout.cshtml"
       RenderBody(); 

#line default
#line hidden
            WriteLiteral("</body>\r\n</html>\r\n");
        }
        #pragma warning restore 1998
    }
}
#pragma warning restore 1591
